imports:
    - { resource: tables.yml }

services:
    rmcgirr83.nationalflags.admin.controller:
        class: rmcgirr83\nationalflags\controller\admin_controller
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @pagination
            - @controller.helper
            - @request
            - @template
            - @user
            - @service_container
            - @ext.manager
            - @path_helper
            - %core.root_path%
            - %core.php_ext%			
            - %rmcgirr83.nationalflags.table.nationalflags%
            - @rmcgirr83.nationalflags.functions

    rmcgirr83.nationalflags.main.controller:
        class: rmcgirr83\nationalflags\controller\main_controller
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @pagination
            - @controller.helper
            - @request
            - @ext.manager
            - @path_helper
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
            - %rmcgirr83.nationalflags.table.nationalflags%
            - @rmcgirr83.nationalflags.functions

    rmcgirr83.nationalflags.listener:
        class: rmcgirr83\nationalflags\event\listener
        arguments:
            - @auth
            - @cache
            - @config
            - @controller.helper
            - @dbal.conn
            - @request
            - @template
            - @user
            - @ext.manager
            - %core.root_path%
            - %core.php_ext%
            - @rmcgirr83.nationalflags.functions
        tags:
            - { name: event.listener }

    rmcgirr83.nationalflags.functions:
        class: rmcgirr83\nationalflags\core\nationalflags
        arguments:
            - @config
            - @controller.helper
            - @cache
            - @dbal.conn
            - @template
            - @user
            - %rmcgirr83.nationalflags.table.nationalflags%
            - @ext.manager
            - @path_helper